#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const input = userInputs[3]
const edit = userInputs[4]

switch (cmd) {
  case 'list':
    commands.list()
    break

  case 'display':
    commands.displayId(input)
    break

  case 'displayOwner':
    commands.displayTaskByOwner(input)
    break

  case 'delete':
    commands.deleteTask(input)
    break

  case 'insert': {
    const owner = input
    const task = edit
    commands.insertTask(owner, task)
    break
  }

  case 'update':
    commands.editTask(input, edit)
    break

  case 'search':
    commands.searchTask(input)
    break

  case 'completed':
    commands.completeTask(input)
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}
