#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const arg = userInputs[3]

switch (cmd) {
  case 'list':
    commands.list()
    break

  case 'display':
    commands.display(arg)
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}
